---
title: "Exploratory Data Analysis"
output:
  html_notebook: default
  html_document:
    df_print: paged
  pdf_document: default
---


```{r}
plot(cars)
```
```{r}
mtcars
```
```{r}
head(mtcars)
```

```{r}
link_to_dataset <- "https://raw.githubusercontent.com/HackBio-Internship/public_datasets/main/R/small_file.txt"

smallFile <- read.table(file =link_to_dataset, header = TRUE)
```

```{r}
summary(smallFile)
```


### The Tooth Growth Datasets

```{r}
MyToothGrowth <- ToothGrowth
head(MyToothGrowth)
```


```{r}
dim(MyToothGrowth)
```

```{r}
names(MyToothGrowth)
```

```{r}
str(MyToothGrowth)
```
### Descriptive statistics

```{r}
summary(MyToothGrowth)
```
### Relationship Between Variables

```{r}
plot(MyToothGrowth$len)
barplot(MyToothGrowth$len)
plot(MyToothGrowth$len, col = factor(MyToothGrowth$supp))
plot(MyToothGrowth$len, col = factor(MyToothGrowth$dose))
```


```{r}
boxplot(len~dose, data = MyToothGrowth, xlab = "Dose", ylab = "Length",
        col = 4, notch = T)
```
The supplements are dose responsive

```{r}
par(mfrow = c(1,2))

with(subset(MyToothGrowth, supp == "OJ"),
      boxplot(len~dose, xlab = "Dose", main = "Orange Juice", ylab = "Length of Tooth", ylim = c(0,40),
              col = "orange", notch = T))

with(subset(MyToothGrowth, supp == "VC"),
      boxplot(len~dose, xlab = "Dose", main = "Vit. c", ylab = "Length of Tooth", ylim = c(0,40),
              col = "blue", notch = T))
```

```{r}
par(mfrow = c(1,3))

with(subset(MyToothGrowth, dose == 0.5),
      boxplot(len~supp, xlab = "Supplement", ylab = "Length of Tooth", main = "At dose 0.5", 
              col = "orange", ylim = c(0,40)))

with(subset(MyToothGrowth, dose == 1.0),
      boxplot(len~supp, xlab = "Supplement", ylab = "Length of Tooth", main = "At dose 1.0", 
              col = "orange", ylim = c(0,40)))

with(subset(MyToothGrowth, dose == 2.0),
      boxplot(len~supp, xlab = "Supplement", ylab = "Length of Tooth", main = "At dose 2.0", 
              col = "orange", ylim = c(0,40)))
```

